package com.ytdlpjava.processor;

import com.ytdlpjava.util.DictionaryLoader;
import com.ytdlpjava.util.LemmatizerService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class SubtitleCleanerTest {

    private SubtitleCleaner createCleaner(int gap, String lang) {
        LemmatizerService.Language language = "ru".equals(lang) ? LemmatizerService.Language.RU : LemmatizerService.Language.EN;
        
        List<String> stopWords = new ArrayList<>();
        stopWords.addAll(DictionaryLoader.load("/dictionaries/stop_words_ru.txt"));
        if ("en".equals(lang)) {
            stopWords.addAll(DictionaryLoader.load("/dictionaries/stop_words_en.txt"));
        }
        
        return new SubtitleCleaner(
                gap,
                language,
                new SubtitleParser(),
                new SubtitleCleanerService(DictionaryLoader.load("/dictionaries/fillers.txt")),
                new KeywordExtractor(stopWords, new LemmatizerService(), language),
                new KeywordHighlighter(),
                new MarkdownFormatter()
        );
    }

    @Test
    void testCleanVttToText(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(2, "en");
        Path vttPath = tempDir.resolve("test.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:04.000\n" +
                "<c.yellow>Hello</c> world!\n" +
                "\n" +
                "00:00:05.000 --> 00:00:08.000\n" +
                "This is a <b>test</b>.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        assertTrue(result.contains("### [00:00:01]"));
        assertTrue(result.contains("Hello world!"));
        assertTrue(result.contains("### [00:00:05]"));
        assertTrue(result.contains("This is a test."));
    }

    @Test
    void testKeywordsExtraction(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(10, "en");
        Path vttPath = tempDir.resolve("keywords.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:10.000\n" +
                "Apple is a fruit. Apple is red. Apple is sweet.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Keywords Result:\n" + result);
        
        assertTrue(result.contains("**Apple**"), "Keywords should be bolded");
        assertTrue(result.contains("### Ключевые слова:"), "Should contain summary section");
        assertTrue(result.contains("- **apple**: 3"), "Should count apple correctly");
    }

    @Test
    void testAutoGeneratedSubtitles(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(2, "en");
        Path vttPath = tempDir.resolve("auto.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:00.000 --> 00:00:01.000\n" +
                "hello\n" +
                "\n" +
                "00:00:01.000 --> 00:00:02.000\n" +
                "world\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Auto Result:\n" + result);
        assertTrue(result.contains("Hello world"));
    }

    @Test
    void testScrollingSubtitles(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(10, "en");
        Path vttPath = tempDir.resolve("scroll.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:02.000\n" +
                "Line 1\n" +
                "\n" +
                "00:00:02.000 --> 00:00:03.000\n" +
                "Line 1\n" +
                "Line 2\n" +
                "\n" +
                "00:00:03.000 --> 00:00:04.000\n" +
                "Line 2\n" +
                "Line 3\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Scroll Result:\n" + result);
        assertTrue(result.contains("Line 1") || result.contains("**Line** 1"));
    }

    @Test
    void testFillerWordsRemoval(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(2, "ru");
        Path vttPath = tempDir.resolve("filler.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:04.000\n" +
                "Привет, ну, это как бы тест.\n" +
                "\n" +
                "00:00:05.000 --> 00:00:08.000\n" +
                "Я э-э занимаюсь этим э-э сейчас.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Filler Result:\n" + result);
        
        assertFalse(result.contains("ну"));
        assertFalse(result.contains("как бы"));
        assertFalse(result.contains("э-э"));
        assertTrue(result.contains("Привет, это тест"));
        assertTrue(result.contains("Я занимаюсь этим сейчас"));
    }

    @Test
    void testSmartJoining(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(1, "ru");
        Path vttPath = tempDir.resolve("join.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:02.000\n" +
                "Это незаконченное\n" +
                "\n" +
                "00:00:03.000 --> 00:00:04.000\n" +
                "предложение.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Join Result:\n" + result);
        
        assertTrue(result.contains("предложение"));
        assertFalse(result.contains("Предложение"));
    }

    @Test
    void testLineWrapping(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(10, "en");
        Path vttPath = tempDir.resolve("wrap.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:10.000\n" +
                "This is a very long line that should definitely be wrapped into multiple lines because it exceeds the ninety-five character limit that we have set in our cleaner implementation for better readability.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Wrap Result:\n" + result);
        
        String[] resultLines = result.split("\n");
        for (String line : resultLines) {
            if (!line.startsWith("#") && !line.startsWith("-") && !line.startsWith("---") && !line.isEmpty()) {
                assertTrue(line.length() <= 100, "Line is too long: " + line.length() + " -> " + line);
            }
        }
    }

    @Test
    void testDaFillerAndPunctuation(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(10, "ru");
        Path vttPath = tempDir.resolve("punctuation.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:10.000\n" +
                "в будущем, да, для того,. чтобы мы с\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Punctuation Result:\n" + result);
        
        assertFalse(result.contains(",. "), "Should not contain ',.'");
        assertFalse(result.contains(" да, "), "Should remove 'да'");
    }

    @Test
    void testNewFillersAndPrepositionDot(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(10, "ru");
        Path vttPath = tempDir.resolve("new_fillers.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:10.000\n" +
                "возвращаясь с. Победою домой эм я ам ээ пришел\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("New Fillers Result:\n" + result);
        
        assertFalse(result.contains("с."), "Should remove dot after 'с'");
        assertFalse(result.contains("эм"), "Should remove 'эм'");
        assertFalse(result.contains("ам"), "Should remove 'ам'");
        assertFalse(result.contains("ээ"), "Should remove 'ээ'");
        assertTrue(result.contains("возвращаясь с Победою домой я пришел") || result.contains("Возвращаясь с Победою домой я пришел"));
    }

    @Test
    void testKeywordExclusion(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = createCleaner(10, "ru");
        Path vttPath = tempDir.resolve("exclude.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:10.000\n" +
                "Человек говорит тебе о себе. Свое слово он сказал нас в мире жизни. Нет где почему дальше всем нас.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Exclusion Result:\n" + result);
        
        // Informative words should be keywords
        assertTrue(result.contains("**Человек**") || result.contains("**человек**"));
        assertTrue(result.contains("**Жизни**") || result.contains("**жизни**"));
        
        // Pronouns and noise should NOT be in the "Ключевые слова" summary
        assertFalse(result.contains("- **тебе**"), "Should exclude 'тебе'");
        assertFalse(result.contains("- **себе**"), "Should exclude 'себе'");
        assertFalse(result.contains("- **свое**"), "Should exclude 'свое'");
        assertFalse(result.contains("- **нас**"), "Should exclude 'нас'");
        assertFalse(result.contains("- **нет**"), "Should exclude 'нет'");
        assertFalse(result.contains("- **где**"), "Should exclude 'где'");
        assertFalse(result.contains("- **поч**"), "Should exclude 'почему' (stem: поч)");
        assertFalse(result.contains("- **дальш**"), "Should exclude 'дальше' (stem: дальш)");
        assertFalse(result.contains("- **все**"), "Should exclude 'всем' (stem: все)");
    }
}
