package com.ytdlpjava;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import static org.junit.jupiter.api.Assertions.*;

class SubtitleCleanerTest {
    @Test
    void testCleanVttToText(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = new SubtitleCleaner(2);
        Path vttPath = tempDir.resolve("test.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:04.000\n" +
                "<c.yellow>Hello</c> [Music] world!\n" +
                "\n" +
                "00:00:05.000 --> 00:00:08.000\n" +
                "This is a <b>test</b>.\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        assertTrue(result.contains("[00:00:01]"));
        assertTrue(result.contains("Hello world!"));
        assertTrue(result.contains("[00:00:05]"));
        assertTrue(result.contains("This is a test."));
    }

    @Test
    void testAutoGeneratedSubtitles(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = new SubtitleCleaner(2);
        Path vttPath = tempDir.resolve("auto.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:00.000 --> 00:00:01.000\n" +
                "hello\n" +
                "\n" +
                "00:00:01.000 --> 00:00:02.000\n" +
                "world\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Auto Result:\n" + result);
        
        long dotCount = result.chars().filter(ch -> ch == '.').count();
        assertTrue(dotCount <= 1, "Should have at most one dot for a short sentence, but found " + dotCount);
    }

    @Test
    void testScrollingSubtitles(@TempDir Path tempDir) throws IOException {
        SubtitleCleaner cleaner = new SubtitleCleaner(10); // High gap to keep them in one block
        Path vttPath = tempDir.resolve("scroll.vtt");
        String vttContent = "WEBVTT\n" +
                "\n" +
                "00:00:01.000 --> 00:00:02.000\n" +
                "Line 1\n" +
                "\n" +
                "00:00:02.000 --> 00:00:03.000\n" +
                "Line 1\n" +
                "Line 2\n" +
                "\n" +
                "00:00:03.000 --> 00:00:04.000\n" +
                "Line 2\n" +
                "Line 3\n";
        Files.writeString(vttPath, vttContent);

        String result = cleaner.process(vttPath);
        
        System.out.println("Scroll Result:\n" + result);
        
        assertTrue(result.contains("Line 1 Line 2 Line 3"), "Should de-duplicate scrolling lines");
        assertFalse(result.contains("Line 1 Line 1"), "Should not have repeated Line 1");
        assertFalse(result.contains("Line 2 Line 2"), "Should not have repeated Line 2");
    }
}
